name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Create iOS Project
        run: flutter create . --platforms=ios

      - name: Install Dependencies
        run: flutter pub get

      - name: Build Payload IPA
        run: |
          flutter build ios --release --no-codesign
          mkdir Payload
          mv build/ios/iphoneos/Runner.app Payload/
          zip -r AradServer.ipa Payload

      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.0
          files: AradServer.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
